trigger: none

parameters:
  - name: customer
    displayName: Customer
    type: string
    values:
      - koen
      - martin
  - name: appVersion
    displayName: App version
    type: string

stages:
- stage: Deploy
  jobs:
    - deployment: deploy_sample_app
      displayName: 'Deployment sample app'
      environment: 
        name: 'local-kubernetes-dev'
      pool: 
        name: Local-kubernetes
        demands: 
          - DEF_TYPE -equals deploy
          - DEF_CUSTOMER_NAME -equals ${{ parameters.customer }}
      strategy:
        runOnce:
          deploy:
            steps:
              - task: UsePythonVersion@0
                inputs:
                  versionSpec: '3.9'
                  architecture:  'x64' 
                  disableDownloadFromRegistry: true
                  addToPath: true
                displayName: 'Use Python 3.9' 

              - script: |
                  python -m pip install --upgrade pip
                  pip install artifacts-keyring
                displayName: 'Install dependency'

              - task: PipAuthenticate@1
                displayName: Login to feed
                inputs:
                  artifactFeeds: learning/sample-app
                  onlyAddExtraIndex: true

              - script: |
                  pip install python-sample-app==${{ parameters.appVersion }}
                displayName: 'Install app'